### ISSUE TITLE
Evaluating experiment tracking adoption

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1390]
## Description
We shipped the first iteration of [experiment tracking](https://kedro.readthedocs.io/en/stable/03_tutorial/07_set_up_experiment_tracking.html) towards the end of November and we would like to understand why the feature has not been adopted. @NeroOkwa is leading this fantastic work. 

## Hypotheses
We suspect that Experiment Tracking is not being used because:
 - There is a lack of awareness about the functionality, including that our outreach was not focused enough on targeted users 
 - A subset of users, [using Windows computers, cannot use the functionality](https://github.com/kedro-org/kedro-viz/issues/763)
 - Users still prefer using MLflow for experiment tracking 
 - They haven't upgraded their version of Kedro; this reason was raised by @Galileo-Galilei
 - They might not need the functionality, which would be counterintuitive to our previous research #1070 

<img width="493" alt="Screenshot 2022-03-30 at 15 58 53" src="https://user-images.githubusercontent.com/43755008/160865913-d892015c-3788-4dad-9dfb-1a1338dce311.png">

## Possible Implementation
We're going to structure our research by finding target populations: 
 - Our reference users that the feature was built with
 - Our poll respondents; that needs to be segmented
 - Users which have run `kedro viz` from their CLI
 - Users who could be on Discord that haven't used the feature

We're going to approach these user groups in the following ways:
 - Our reference users that the feature was built with: We need to let this group know that the feature is active and running (One of the reference users knows already @Galileo-Galilei) 
 - Our poll respondents that have experiment tracking on their list to try need to be nudged and encouraged to use the feature; might need to help them set it up on their project
 - Our poll respondents that had no awareness of experiment tracking need to have an introductory session
 - Our users that have run `kedro viz` from their CLI, we can schedule interviews and potentially run a survey with this group

**Actions to do:**

- [x] Organise new set of questions to put to new groups
- [x] Invent system to ensure we don't speak to users twice / annoy them. Set up on Airtable. 
- [x] Decide strategy of interviews (based on `kedro-viz` users)— quantity vs quality based on user groups (surveys vs 1to1s)
- [x] Plan walkthroughs for those that need it
- [x] Launch poll on Discord
- [x] Get list of `kedro-viz` users

## Measure of Success in 3 Months
- 100 users of experiment tracking
- Five presentations on "How I used Experiment Tracking in my workflow?" 

## Additional data 

From @yetudada to @Galileo-Galilei: You were also part of our user testing for Experiment Tracking in Kedro. I want to [show you how to set it up (unfortunately it’s only available from Kedro 0.17.5)](https://kedro.readthedocs.io/en/latest/03_tutorial/07_set_up_experiment_tracking.html) and the [demo](https://demo.kedro.org/runsList). 

From @Galileo-Galilei to @yetudada: We have not been using it for now for several reasons:
- We are still using `kedro==0.16.5` for now because we have legacy projects in production and we do not want to add extra maintenance burden (we have dozens of projects in production + internal plugins , so migration is not a cost we can pay very often). We plan to move to 0.18.x by the end of the year, but we want to wait a little to assess the migration impacts and be sure the version is stable.
- We still use `mlflow` in production, and we don’t have time for testing extensively this new functionality for now. I think we will not use it before 2023.
- But for what it’s worth, we are following the developments and hopefully give it a quick try after our 0.18.x migration.

**Comment by yetudada** [comment]
I'll close this 🥳 This research is complete.
