### ISSUE TITLE
Improve logging setup in Kedro

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#1461]
Currently Kedro has some issues with the logging setup, which can cause some problems from minor annoyances to failures to run a Kedro project in certain environments. Here is a small list of the problems our current logging setup causes:

- Kedro logs at root level, rather than `kedro.*` in many places
- `root` log level is set to `INFO` instead of `WARNING` on all official starters
- on read-only file systems Kedro projects fail to execute, rather than just failing to write the logs
- `KedroSession` logs useless things at `INFO` level, like e.g. that the default session store doesn’t have a `read()` method and `git describe` failures…
- maybe I am mistaken, but I think Kedro logs things before the logging config is setup (to be confirmed).
- CLI commands output too many things, e.g. when you do `kedro catalog list` it should only show the output so it can be machine readable, but now there's lots of `DEBUG` level worthy output
- kedro leaves `info.log` files everywhere for unknown reasons (easiest to notice is when runing a notebook in `notebooks/`)
- https://github.com/kedro-org/kedro-plugins/issues/13

In order to address those issues, we need to work on the following:

- [x] #1472
- [x] #1470
- [x] #1469
- [x] #1473
- [x] #1474
- [x] ~Remove file handlers, special case `kedro.framework.cli.hooks.manager` handler and add documentation on how to setup logging with them (**only if #1472 shows we should remove them**)~
- [x] #1558
- [x] #1512
- [x] #1513
- [x] #1514
- [x] #1575
- [x] #1515
- [x] https://github.com/kedro-org/kedro-plugins/issues/31
- [x] #1683
- [ ] Consider whether to set `spaceflights` log level to `INFO` on framework-side rather than project. Like point 2 of https://github.com/kedro-org/kedro/issues/1469. Needs to use `PACKAGE_NAME`?
- [ ] Work out whether we should have a verbosity flag to change logging level (note we already have a verbosity option on some commands, but it looks like it only changes how detailed `KedroCliError` message is). Otherwise there's no way you will see `DEBUG` level messages emitted by logging calls before `session._setup_logging` is called, even if you alter your project logging.yml to show `DEBUG` level messages. e.g. https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
- [ ] https://github.com/kedro-org/kedro/issues/1464
- [ ] kedro-org/kedro/issues/1728 - should rich stuff be moved to hooks anyway? See also my thoughts on spark hooks

**Comment by AntonyMilneQB** [comment]
For reference, some PRs where I tried to fix some of these things before. I wrote my findings up in the PRs at the time, so I'll re-read these to figure out better what we should do here:
* I thought I fixed lots of logging stuff in https://github.com/kedro-org/kedro/pull/1024
* ...but actually that didn't work so I tried again in https://github.com/kedro-org/kedro/pull/1058
* ...which also didn't work so I reverted all my changes and gave up in https://github.com/kedro-org/kedro/pull/1081

**Comment by noklam** [comment]
In general, I am fine with most of the items
> Ensure logging.yml is optional and remove it from all starters
I like that Kedro is getting lean but I am not sure if I like the idea that the user needs to put the file back to the corresponding location in order to customize it (Although for `logging.yml` I doubt there are many people customize it).  

But it is the same thing for `cli.py`, it's not obvious that you can extend the CLI by creating a new `cli.py` out of nowhere.

Is this a workaround to maintain backward compatibility or we prefer users to customize with this approach? or we should gradually move things to `settings.py`?

> Remove the file-based logging handlers by default
Personally, I like the RotatingFile handler quite a lot, and IMO it's something that people are not using enough. It could be a life-saver when I am running a lot of experiments (especially without a proper experiment tracking tool). Search in a single file is very handy. Are we removing this because we no longer think this is a good default?

**Comment by AntonyMilneQB** [comment]
Thanks for the comments @noklam! 

> I like that Kedro is getting lean but I am not sure if I like the idea that the user needs to put the file back to the corresponding location in order to customize it (Although for `logging.yml` I doubt there are many people customize it).  
> But it is the same thing for `cli.py`, it's not obvious that you can extend the CLI by creating a new `cli.py` out of nowhere.
> Is this a workaround to maintain backward compatibility or do we prefer users to customize with this approach? or we should gradually move things to `settings.py`?

This is a very fair point, and I'm also not sure about the removal of cli.py and hooks.py for the same reasons (like you say, logging.yml seems less important though). It's a balance between:
* the kedro template should be simple for beginner users (in the past there's generally been feedback that it's too overwhelming)
* it should be clear for advanced users that they _can_ customise their kedro project, e.g. by modifying cli.py and logging.yml if they want to

If we don't supply some template (even blank file with comments) logging.yml or cli.py then we need to make it very clear in the documentation that a user can customise their project this way and make it easy for them to copy and paste an example file to do so. Currently we don't emphasise this enough I think.

settings.py is the new way to customise things in kedro, but not everything belongs in there. e.g. I don't think logging configuration would go there because it's run time configuration:
![image](https://user-images.githubusercontent.com/49395058/164743880-63738231-86eb-407a-8dd3-529775e0abaa.png)

> Personally, I like the RotatingFile handler, and IMO it's something that people are not using enough. It could be a life-saver when I am running a lot of experiments (especially without a proper experiment tracking tool). Searching in a single file is very handy even when I have a full experiment tracking setup.
> Are we removing this because we no longer think this is a good default?

Definitely understand this and I also like the file-based logging. I think the problems are:
* practical: it crashes on read-only file systems like databricks repos. I don't think it's possible to just catch and ignore these errors (but we should check that)
* philosophical: [a 12 factor app shouldn't have responsibility for logging](https://12factor.net/logs) (although in practice maybe it's best to make user lives easier by logging to a file)

Again, if we do remove this then I think we need to make it very clear in documentation how a user can create a logging.yml that will do file-based logging.

**Comment by AntonyMilneQB** [comment]
For those not already familiar with it, here's how the logging setup in kedro currently works:
1. Right at the beginning, as soon as you call any `kedro` command from the CLI we setup the default logger:
https://github.com/kedro-org/kedro/blob/35e4ac544a06558e30a41ccd601e37de1afaac14/kedro/framework/cli/cli.py#L16
This sets up logging according to the framework-side logging config in [kedro/config/logging.yml](https://github.com/kedro-org/kedro/blob/676600c4b63eec53c13fc4e2536d0a990dac77ce/kedro/config/logging.yml)
2. Anything that is logged at this point follows the framework-side logging config
3. When a session is created, the project-side logging config in your project's [conf/base/logging.yml](https://github.com/kedro-org/kedro/blob/676600c4b63eec53c13fc4e2536d0a990dac77ce/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/conf/base/logging.yml) is loaded. This is achieved by:
https://github.com/kedro-org/kedro/blob/676600c4b63eec53c13fc4e2536d0a990dac77ce/kedro/framework/session/session.py#L190
The reason this happens relatively late on in the process (i.e. not right at the beginning) is because it needs the config loader available (e.g. to load logging.yml from a different environment, not that anyone ever does that). 
4. Anything that is logged at this point follows the project-side logging config

The above process will not change in any of the issues mentioned here. It's just that users will by default no longer _need to_ (but still _can_) provide a project-side logging.yml file. This will make steps 3 and 4 above disappear for anyone who hasn't setup custom logging by providing a project-side logging.yml file, since the framework-side logging config will be loaded and not altered.

**Comment by AntonyMilneQB** [comment]
The outcome of #1472, which showed that people _do_ use the log files, unfortunately makes some of the simplification that was planned here difficult:
1. We should maintain the current behaviour in which we log to files.
2. One way of handling this is to ensure that the appropriate file handlers are activated in the framework-side logging.yml. Users would then need to create/modify their project-side logging.yml to disable file-based logging (e.g. on databricks repos).
3. Defining the file-based logging on the framework side is unfortunately very awkward though. [Python file-based loggers are able to create a file that they look to but not a directory structure](https://stackoverflow.com/questions/20666764/python-logging-how-to-ensure-logfile-directory-is-created). So we need to either (a) log to `info.log`/`errors.log` in the project root (seems ugly) or (b) write our own custom log handler that creates the directory (easy but annoying means one more piece to maintain) or (c) ensure that no logging takes place before the project-side logging.yml is loaded (impossible if file-based logging is applied to root logger).
4. None of these seem like good solutions, and arguably running a kedro project in package mode shouldn't create log files (or need a log directory) anyway.
5. Hence we should define the file-based handlers in the project-side logging.yml. The downside of this is that the default template cannot immediately be simplified, since removing the project-side logging.yml would remove the file-based logging that it seems most users want. Users who need to disable file-based logging will need to modify their project-side logging.yml as in point 2.

So the plan in https://github.com/kedro-org/kedro/issues/1469 changes as follows:
* alter h to remove file-based handlers from the framework-side logging configuration and keep it in the project-side logging

One advantage of this approach is that it is quite minimal compared to how things currently stand. Hence future changes that could simplify the project template here are still possible.

**Comment by AntonyMilneQB** [comment]
Rough notes to be written up into a new issue in due course...

* Issue with console markup going to file logs: #1663
* Could implement `[dataset]` as in https://github.com/kedro-org/kedro/issues/1514 (would suffer same problem)
* Could change more log messages as per #1514 and https://github.com/kedro-org/kedro/issues/1464, e.g. nice kedro logo, project name message at beginning
* Best solution is probably to add methods that format nodes/datasets nicely by defining a new method: 
https://rich.readthedocs.io/en/stable/pretty.html#rich-repr-protocol https://rich.readthedocs.io/en/stable/protocol.html
* Also consider file logging again (last time polled, these were quite well used): https://github.com/kedro-org/kedro/issues/1472
  * error.log does not seem helpful as it only includes the initial error line, not the traceback (not a change due to adding rich; it's always been like this)
  * consider logging using [rich export functionality instead](https://rich.readthedocs.io/en/stable/console.html#exporting), e.g.
```
from rich import reconfigure
from rich import get_console

class Hooks:
    @hook_impl
    def after_context_created(self):
        reconfigure(record=True)

    @hook_impl
    def after_pipeline_run(self):
        get_console().save_html("logs.html")

```

**Comment by AntonyMilneQB** [comment]
Milestone completed and outstanding issues moved to 
[Tweak logging to improve UX](https://github.com/kedro-org/kedro/milestone/14)
[Complete rich-ification of kedro](https://github.com/kedro-org/kedro/milestone/15)
