### ISSUE TITLE
[Parent] - Logging related issues 

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1735]
## Description
There are a few issues coming up with logging, I thought it may be easier to trace and find workarounds in a parent issue. We had #1461 but it doesn't feel right to append these issues there, they aren't necessary development tasks.

# Issues
- [ ] #1733 
- [x] #1732
- [x] #1729 (rich PR: https://github.com/Textualize/rich/pull/2424)
- [ ] #1719
- [x] #1712 (rich PR: https://github.com/Textualize/rich/pull/2414)
- [x] #1750
- [ ] #1752 
- [x] #1728 
  - [x] Rich traceback doesn't work in databricks: https://github.com/kedro-org/kedro/pull/1769 and https://github.com/Textualize/rich/issues/2455
  - [ ] @mjmare PyCharm issue

**Comment by AntonyMilneQB** [comment]
Closing in favour of [Tweak logging to improve UX](https://github.com/kedro-org/kedro/milestone/14).
