### ISSUE TITLE
Enhance DataSet API Documentation example 

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1762]
We want to improve our DataSet API documentation with examples of **both** YAML and Python API. When possible, the examples should be:
* Simple and minimal
* For Python API, it should be easy to copy & paste and run without error
* Optionally, we can include more advanced examples

PRs are very welcomed🙏🏼!  You don't need to take all the DataSet at once.

# Contributor Guide
You can find our [Contributor Guide](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) on how to setup `kedro` locally and make changes and PR.

# DataSet API ordered base on usage
- [x] [ParquetDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.dask.ParquetDataSet.html#kedro.extras.datasets.dask.ParquetDataSet)(In progress: #1844 )
- [x]  [APIDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.api.APIDataSet.html#kedro.extras.datasets.api.APIDataSet) (In progress: #1844 )
- [x] [pandas.FeatherDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.FeatherDataSet.html#kedro.extras.datasets.pandas.FeatherDataSet)(In progress: #1844 )
- [x] [yaml.YAMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.yaml.YAMLDataSet.html#kedro.extras.datasets.yaml.YAMLDataSet)(In progress: #1844 )
- [x] [tracking.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tracking.JSONDataSet.html#kedro.extras.datasets.tracking.JSONDataSet)(In progress: #1844 )
- [x] [tracking.MetricsDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tracking.MetricsDataSet.html#kedro.extras.datasets.tracking.MetricsDataSet)(In progress: #1844 )
- [x] [TensorFlowModelDataset](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tensorflow.TensorFlowModelDataset.html#kedro.extras.datasets.tensorflow.TensorFlowModelDataset)(In progress: #1844 )

Less common datasets:
- [ ] [TextDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.text.TextDataSet.html#kedro.extras.datasets.text.TextDataSet)
- [ ] [networkx.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.JSONDataSet.html#kedro.extras.datasets.networkx.JSONDataSet)
- [ ] [GraphMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.GraphMLDataSet.html#kedro.extras.datasets.networkx.GraphMLDataSet)
- [ ]  [GMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.GMLDataSet.html#kedro.extras.datasets.networkx.GMLDataSet)
- [x] [MatplotlibWriter](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.matplotlib.MatplotlibWriter.html#kedro.extras.datasets.matplotlib.MatplotlibWriter)
- [ ] [HoloviewsWriter](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.holoviews.HoloviewsWriter.html#kedro.extras.datasets.holoviews.HoloviewsWriter)
- [ ]  [GeoJSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.geopandas.GeoJSONDataSet.html#kedro.extras.datasets.geopandas.GeoJSONDataSet)
- [ ] [EmailMessageDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.email.EmailMessageDataSet.html#kedro.extras.datasets.email.EmailMessageDataSet)
- [ ] [BioSequenceDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.biosequence.BioSequenceDataSet.html#kedro.extras.datasets.biosequence.BioSequenceDataSet)
- [ ] [XMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.XMLDataSet.html#kedro.extras.datasets.pandas.XMLDataSet)
- [ ] [ImageDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.XMLDataSet.html#kedro.extras.datasets.pandas.XMLDataSet)
- [ ] [plotly.PlotlyDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.plotly.PlotlyDataSet.html#kedro.extras.datasets.plotly.PlotlyDataSet)
- [ ] [plotly.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.plotly.JSONDataSet.html#kedro.extras.datasets.plotly.JSONDataSet)

_Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/579#issuecomment-1102384971_, slightly edited

**Comment by levimjoseph** [comment]
@noklam FYI still working but will tag to this ticket.

**Comment by noklam** [comment]
@levimjoseph Awesome, feel free to make a draft PR when you have something, it doesn't have to be completely ready so we have a chance to have a look at it. As this could become a big PR.

**Comment by noklam** [comment]
@BitGeek29 Hey,  PR is very welcomed!  I don't think this can be addressed in one big PR,  but would be good to know @levimjoseph  which datasets are u working on?

I would love to see a draft PR even if it's not ready,  this way we have better idea what's happening and help out if needed!

**Comment by levimjoseph** [comment]
@noklam sorry I went dark. Some personal life stuff came up.

I will put up a draft PR today! It will have all of the prioritized datasets.

**Comment by levimjoseph** [comment]
@noklam just put up a new PR. Sorry for some sloppy git behavior (was working through my env setup.

**Comment by MerelTheisenQB** [comment]
Anyone coming here through **Hacktoberfest**: feel free to add examples to any of the datasets listed under "Less common datasets:" in the description. There's no need to add examples for all of them in one go.

**Comment by noklam** [comment]
@BitGeek29 Hey, are you still interested to work on this issue? :D

**Comment by BitGeek29** [comment]
No, if like you can take it.

**Comment by amaralbf** [comment]
Hi, @noklam, just created a draft PR (#1945) with changes to the MatplotlibWriter Dataset documentation (my first PR ever 😄).

**Comment by luizvbo** [comment]
Hi everyone! 

I saw this message when I opened the PR:
> Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.

I have added examples for text.TextDataSet, plotly.PlotlyDataSet and plotly.JSONDataSet. Should I create a PR in the kedro-plugins repo instead?

**Comment by noklam** [comment]
@luizvbo Sorry for the late reply. If it's a quick one you can still open in this repository, at the moment we are trying to migrate, once we finished we expect all new changes go to `kedro-datasets`

**Comment by noklam** [comment]
The related PRs are merged and we had separate issues to improve the DataSet docs
