### ISSUE TITLE
Parent task: Set up subprojects for Kedro-Viz and kedro-datasets docs

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2600]
We are thinking about using a subproject for Viz docs to enable them to be versioned according to the Viz release and updated along with those releases rather than linked to Framework release schedules. 

The team plan to make multiple releases for collaborative experiment tracking and would like to manage the docs for different versions autonomously. We'd publish to https://docs.kedro.org/kedro-viz

However, does RTD support subproject is in a different repo? I've only seen mention of subprojects being in a single repo? As far as we can tell, this should be fine, and should be a useful model for other docs like those for datasets and other plugins. We need to run a pilot to see if it's feasible to do this, and how long it'll take.

**Comment by astrojuanlu** [comment]
> Or would it make more sense to have the Viz docs themselves in the Viz repo and use that as the subproject?

This is what we have in mind. The process would be like this:

1. Create a Sphinx project in kedro-viz
2. Create a RTD project for kedro-viz
3. Use that RTD project as subproject of kedro
4. Profit

It _should_ work.

**Comment by tynandebold** [comment]
Great. Let me know if I can help.

**Comment by tynandebold** [comment]
I've added you. You should have an invite in your inbox.

**Comment by astrojuanlu** [comment]
Got access 🙌🏽

**Comment by astrojuanlu** [comment]
> :rocket: We shipped support for customizing the URL path for projects and subprojects, allowing you to remove or customize the /projects/ path on subprojects. This is enabled via Support request currently, and only on certain plans on Read the Docs for Business.

https://blog.readthedocs.com/newsletter-july-2023/

**Comment by astrojuanlu** [comment]
Subprojects for kedro-datasets and kedro-viz are created

- https://docs.kedro.org/projects/kedro-viz/en/latest/
- https://docs.kedro.org/projects/kedro-datasets/en/latest/

Follow up tasks:

- [ ] Fix the builds, for which we need to set up distinct Heap properties for each subproject
- [ ] Fix the styling so they use exactly the same theme as the Kedro docs, might require refactoring our Sphinx theme into a separate package for easier reuse
- [ ] Include links from the subprojects back to Kedro
- [ ] Include links from the Kedro docs to the subprojects - these could be in the same left navigation bar we have currently, or a top navigation bar if we happen to tackle https://github.com/kedro-org/kedro-viz/issues/1474 first

**Comment by stichbury** [comment]
> Follow up tasks:
> 
> * [ ]  Fix the builds, for which we need to set up distinct Heap properties for each subproject
> * [ ]  Fix the styling so they use exactly the same theme as the Kedro docs, might require refactoring our Sphinx theme into a separate package for easier reuse
> * [ ]  Include links from the subprojects back to Kedro
> * [ ]  Include links from the Kedro docs to the subprojects - these could be in the same left navigation bar we have currently, or a top navigation bar if we happen to tackle [Improve the usability of the Framework documentation home page kedro-viz#1474](https://github.com/kedro-org/kedro-viz/issues/1474) first

I'll make tickets for each of these shortly and prioritise them as this is something I want us to complete sooner rather than later. I think it's likely we'll do this and return to #1474 so we may need to have an interim solution to link between docs and add a requirement to that task to introduce a better one.

**Comment by astrojuanlu** [comment]
- kedro-datasets https://docs.kedro.org/projects/kedro-datasets/en/kedro-datasets-1.6.0/ ✔️ (but see discussion about the URLs below)
- kedro-viz https://readthedocs.org/projects/kedro-viz/builds/21770555/ ❌ (some dependencies are not in place, but at least the build was attempted)

I'm not very happy with the URL of kedro-datasets though. Ideally we'd have `https://docs.kedro.org/projects/kedro-datasets/en/1.6.0/` but since version slugs come from the tag name (https://github.com/readthedocs/readthedocs.org/issues/4167, https://github.com/readthedocs/readthedocs.org/issues/10674) we would need to resort to workarounds:

- Adapt tag names. But this would require splitting `kedro-datasets` to its own repository, which is an idea that has been met with skepticism in the past.
- Ask the RTD team to modify slugs every time. I don't think this is very sustainable and it's not even guaranteed they'll do this for us.
- Accept that URLs will be like this 🤷🏽

**Comment by stichbury** [comment]
> I'm not very happy with the URL of kedro-datasets though. I've been told that the `/projects` part can be removed, but the last `/kedro-datasets-1.6.0` segment needs to stay, because it comes from the tag name and cannot be changed ([readthedocs/readthedocs.org#4167](https://github.com/readthedocs/readthedocs.org/issues/4167), [readthedocs/readthedocs.org#10674](https://github.com/readthedocs/readthedocs.org/issues/10674)). At the moment, to shorten the URLs we would need to resort to workarounds:
> 
> * Adapt tag names. But we can't just tag `1.6.0` because `kedro-datasets` lives in a monorepo with other projects. We could split `kedro-datasets` to its own repository, but this idea has been met with skepticism in the past. Also, having to do that just because of RTD is weird.
> * Ask the RTD team to modify slugs every time. I don't think this is very sustainable and it's not even guaranteed they'll do this for us.
> * Accept that URLs will be like this 🤷🏽

Can I just check @astrojuanlu why we can't also have `stable` and `latest` for datasets as we do for Viz and Framework?

**Comment by astrojuanlu** [comment]
Because `kedro-datasets` lives on a monorepo 😓 so all the assumptions RTD makes to create `stable` and `latest` break down.

From https://docs.readthedocs.io/en/stable/versions.html

> Read the Docs supports multiple versions of your repository. On initial import, we will create a latest version. This will point at the default branch defined in your VCS control (by default, main on Git and default in Mercurial).
>
> If your project has any tags or branches with a name following [semantic versioning](https://semver.org/), we also create a stable version, tracking your most recent release. If you want a custom stable version, create either a tag or branch in your project with that name.

and tags on https://github.com/kedro-org/kedro-plugins/tags do _not_ follow "semantic versioning", because they're prefixed with the plugin in question.

There are no good options here. We either quit RTD over this (and maintain our own infrastructure capable of versioning docs, which is not an easy feat), or we break down the monorepo into separate repos (that's an engineering decision I'd personally be supportive of, and would solve other things like discoverability https://github.com/kedro-org/kedro-plugins/issues/401), or we accept these terrible URLs.

**Comment by tynandebold** [comment]
My two cents...

> We either quit RTD over this (and maintain our own infrastructure capable of versioning docs, which is not an easy feat)

That seems like a non-starter. I don't imagine we'll have capacity to do this anytime soon, if ever (unless there's a quite simple way of achieving this that I'm not seeing).

> we break down the monorepo into separate repos

I'm in favor of this. I've found it hard to discover some of our plugins, especially datasets. For example, when I search `kedro datasets github` on Google, the **sixth** result is the plugins repo, which isn't exactly what I'm looking for.

And just to throw a wrench in at the end, I don't actually find the URL to be that terrible (https://docs.kedro.org/kedro-datasets/en/kedro-datasets-1.6.0/), though agree that it isn't ideal.

**Comment by astrojuanlu** [comment]
Thanks @tynandebold. xref https://github.com/kedro-org/kedro-plugins/issues/401 for the discoverability issue.

**Comment by stichbury** [comment]
The final PRs to address this parent task are sitting in review:

- [ ] [Framework](https://github.com/kedro-org/kedro/pull/3292)
- [ ] [Viz](https://github.com/kedro-org/kedro-viz/pull/1628)
- [ ] [Plugins](https://github.com/kedro-org/kedro-plugins/pull/400)

**Comment by stichbury** [comment]
These are all now merged 💃 or about to merge. Closing this as (finally) done!
