### ISSUE TITLE
Plan for Renaming DataSet to Dataset

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2740]
# Background
This is a parent issue to document what've been done and what more to be done. This refactoring isn't simple as just changing the name of the class, and the success of this require coordination of dev and marketing. As this also affect various things (kedro.org, blogs for new Dataset contributions)

Done:
- #2500 is the main effort renaming everything from `DataSet` -> `Dataset` except `AbstractDataSet`
- #2673, #2706 are the effort enhancing the Deprecation warning show up but not everywhere.
- #2724 attempts to improve it further with a modern Pythonic way to deprecate classes.

Ongoing:
- #2735 is updating the `DataSet` -> `Dataset` mentions in the markdown docs
- #2746 renames `AbstractDataSet` -> `AbstractDataset`

Things that are missing
- [ ] Update the documentation for `.rst` files in `kedro` https://github.com/kedro-org/kedro/blob/6e5e4e1258fe02f5195c7669b4c469b2706ef2bf/docs/source/kedro.extras.datasets.rst#L4
- [ ] Do we need to update the URL on RTD? Do we need to setup the redirect because it will change the URL. https://kedro-org.slack.com/archives/C054U0LJLAC/p1687467469513519
  - https://docs.kedro.org/en/latest/kedro_datasets.api.APIDataSet.html -> https://docs.kedro.org/en/latest/kedro_datasets.api.APIDataset.html (It is case sensitive) @stichbury 
- [ ] Do we need to update these `extra` install with `Dataset` as well? https://github.com/kedro-org/kedro/blob/6e5e4e1258fe02f5195c7669b4c469b2706ef2bf/setup.py#L44-L50
- [ ] Deprecations warning for `kedro-datasets` (is this needed or we release the `Dataset` version as a breaking change?) I think we need to communicate this and have a better plan. See https://github.com/kedro-org/kedro/issues/2751.
- [ ] Starters
- [ ] Graphic in the Data Catalog section on the website

Questions:
- Do we need to finish all of this before release or we can find some midpoint?
- It is a bit awkward if we start showing `Deprecation` warnings in `kedro` but `kedro-datasets` are still using `DataSet`. Particular for users using `kedro-datasets` already, it may resulted in hybrid `DataSet` and `Dataset` in their `catalog.yml` @deepyaman

**Comment by astrojuanlu** [comment]
More:

- https://github.com/kedro-org/kedro-plugins/pull/253
- https://github.com/kedro-org/kedro-plugins/pull/255

And I agree, the priority should be to not show `DeprecationWarning`s that users can't action on.

**Comment by deepyaman** [comment]
Not sure the way of suppressing warnings is right...

```python
>>> from kedro.io import MemoryDataSet
>>> from kedro.io.memory_dataset import MemoryDataSet
<stdin>:1: DeprecationWarning: 'MemoryDataSet' has been renamed to 'MemoryDataset', and the alias will be removed in Kedro 0.19.0
>>> 
```

We should still show `DeprecationWarning`.

It's annoying, but there's definitely precedent for still showing warnings, even when the user can't control them (like all the numpy warnings because of what libraries that use numpy do). Let me think if there's something better, but I think the lesser of two evils is to raise the warnings.

**Comment by astrojuanlu** [comment]
@deepyaman sorry, I clarify - I was not advocating to suppress the `DeprecationWarning`s. I was advocating for only showing them for code that users wrote, and when there's an alternative. In particular, `kedro-datasets` hasn't been migrated already, but doing `from kedro_datasets.pandas import CSVDataSet` will emit a `DeprecationWarning` that the user can't do anything about. That's what https://github.com/kedro-org/kedro-plugins/pull/255 aims to fix.

**Comment by deepyaman** [comment]
> @deepyaman sorry, I clarify - I was not advocating to suppress the `DeprecationWarning`s. I was advocating for only showing them for code that users wrote, and when there's an alternative. In particular, `kedro-datasets` hasn't been migrated already, but doing `from kedro_datasets.pandas import CSVDataSet` will emit a `DeprecationWarning` that the user can't do anything about. That's what [kedro-org/kedro-plugins#255](https://github.com/kedro-org/kedro-plugins/pull/255) aims to fix.

Understood; so are we saying we can undo the suppression in `kedro/io/__init__.py` then? #2746 is actually semi-choking on that (just a test, I could ignore it), hence why I started looking into it. :)

**Comment by deepyaman** [comment]
> Do we need to update these `extra` install with `Dataset` as well? https://github.com/kedro-org/kedro/blob/6e5e4e1258fe02f5195c7669b4c469b2706ef2bf/setup.py#L44-L50

pip standardizes non-lowercase extras, so this would be a nice change for consistency, but it's not strictly necessary/high priority.

**Comment by zedrdave** [comment]
At the moment, it seems like kedro itself is triggering its own DeprecationWarning:

For example, the `io` package `__init__.py` contains:
`from .cached_dataset import CachedDataset, CachedDataSet`

(and similarly for other renamed `***Dataset` classes)

This does not seem like a desirable behaviour… Or am I missing something?

**Comment by astrojuanlu** [comment]
For reference, @zedrdave question was discussed in https://github.com/kedro-org/kedro/issues/2882

**Comment by astrojuanlu** [comment]
Relevant: https://github.com/kedro-org/kedro-plugins/issues/313

**Comment by zedrdave** [comment]
> For reference, @zedrdave question was discussed in #2882

I do not think these 2 issues are the same.

One has to do with Kedro's import order (which triggers warnings when using custom classes), and the other has to do with the fact that current codebase (as of a month ago) was attempting to load both new and old class names, triggering a DeprecationWarning that users could not do anything about.

**Comment by astrojuanlu** [comment]
Ah, thanks for the clarification @zedrdave, I read too fast 👍🏽

**Comment by merelcht** [comment]
Closing this in favour of https://github.com/kedro-org/kedro/issues/2129 which is the full list of tasks for renaming assuming that datasets have by that point been removed from the core Kedro project.
