### ISSUE TITLE
Kedro release 0.18.13 - official support for Python 3.11

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2919]
We want to do a release by end of this Sprint (21 Aug)/early next sprint. 

### Done (feel free to add the related PR/issues)
- Kedro Python 3.11 support - (need to wait for kedro-datasets https://github.com/kedro-org/kedro-plugins/issues/154)
- The series of fix for starter , kedro pipeline create, kedro catalog create
- Custom resolver for OmegaConf

### Blockers:
- [x] https://github.com/kedro-org/kedro-plugins/issues/290
- [x] https://github.com/kedro-org/kedro-plugins/issues/298 (for Kedro-Viz)
- [x] https://github.com/kedro-org/kedro-plugins/pull/305
- [x] https://github.com/kedro-org/kedro-plugins/issues/306
### Other todo:
- [x] kedro catalog resolve - #2891
- [x] + docs for dataset factories commands - https://github.com/kedro-org/kedro/issues/2849
- [x] https://github.com/kedro-org/kedro-starters/pull/140
- [x] https://github.com/kedro-org/kedro/pull/2889
- [x] datasets 3.11 support https://github.com/kedro-org/kedro-plugins/issues/154
- [x] Viz python 3.11 support https://github.com/kedro-org/kedro-viz/issues/1446
- [x] #2918 
- [x] https://github.com/kedro-org/kedro/pull/2735
- [x] https://github.com/kedro-org/kedro/pull/2746
- [x] https://github.com/kedro-org/kedro/issues/2521
- [x] https://github.com/kedro-org/kedro/issues/2794
- [x] #2976
- [x] https://github.com/kedro-org/kedro-starters/pull/144

Nice to include:
- [x] #2977

**Comment by datajoely** [comment]
+1

**Comment by ankatiyar** [comment]
May I also add https://github.com/kedro-org/kedro/issues/2794, seems to be some demand for this feature on the #questions channel :)

**Comment by noklam** [comment]
It would be nice to include [Stop OmegaConfigLoader from reading config from hidden directory like ipynb_checkpoints](https://github.com/kedro-org/kedro/pull/2977#top) if it's ready, but not mandatory for this release.

**Comment by astrojuanlu** [comment]
Also the migration guide #2904, and keeping an eye on https://github.com/kedro-org/kedro-viz/pull/1502
