### ISSUE TITLE
[PARENT] kedro-datasets tickets for `2.0.0`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3043]
## Introduction

This is an issue tracker to centralised the discussion. (Should roughly take this in order because some tickets has dependencies)
- [x] #2126 @noklam 
- [x] https://github.com/kedro-org/kedro/pull/3060 @noklam 
- [x] #3068 @AhdraMeraliQB 
- [x] #2127 @ankatiyar 
- [x] #2128
- [x] #2125 @AhdraMeraliQB 
- [x] https://github.com/kedro-org/kedro-plugins/issues/249
- [x] #2713 
- [x] #1502 @noklam 
- [x] #1498 
- [x] Nice to have: #2287

**Comment by merelcht** [comment]
Closing this because all tickets (apart from the nice to have) are done.
