### ISSUE TITLE
[Parent] - Add-ons Project Creation flow

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3216]
Milestone: https://github.com/kedro-org/kedro/milestone/33 (To see what's left)

Blocking (Top priority):
- https://github.com/kedro-org/kedro/issues/2975 @DimedS 
- https://github.com/kedro-org/kedro-starters/pull/170 @SajidAlamQB 
- https://github.com/kedro-org/kedro/pull/3230 @noklam 
- https://github.com/kedro-org/kedro-starters/pull/171
- https://github.com/kedro-org/kedro-starters/pull/177 @SajidAlamQB 

This issue is currently blocking all new add-ons Pr (i.e. spark, viz) because we have different template structure in `kedro/templates` and `kedro-starters`.

In Progress:
- [x] https://github.com/kedro-org/kedro/issues/2873 @lrcouto 
- [x] https://github.com/kedro-org/kedro/pull/3188 @noklam (merge this first as refactor affect most add-on flow)
- [x] https://github.com/kedro-org/kedro-starters/pull/175 @merelcht 
- [x] https://github.com/kedro-org/kedro-starters/pull/177 @SajidAlamQB 
- [x] #3268 @SajidAlamQB 

Blocked:
- [x] https://github.com/kedro-org/kedro/issues/3073 @SajidAlamQB 
- [x] https://github.com/kedro-org/kedro/issues/3074 @noklam @SajidAlamQB
- [x] https://github.com/kedro-org/kedro/issues/3075 @SajidAlamQB @AhdraMeraliQB (This is being done in #3074)
- [x] #3076 @DimedS 

Design Ticket:
- https://github.com/kedro-org/kedro/issues/3054

Final:
- [x] Let's do a final spike at the end to try our best to break this workflow
Checking:
- `kedro new` - Should trigger add-ons flow
- `kedro new --add-ons --starter` should trigger an error, invalid combination of options
- `kedro new` + select `pyspark` will pull from `kedro-starters` 
-  Do `kedro run` to test that the created projects can be run successfully.
- "Data Structure" - do we have a better name?
- fill in the correct URLs to the relevant docs for each step of the flow 

Potential Improvement:
- Refactor the logic to a separate `add_on.py`? It started to feel it overcrowd the `starters.py`. Starters still exist as a separate feature but `kedro new` can use either `starter` flow or `add_on`

**Comment by amandakys** [comment]
I've gone for Data Folder in the prototype that i've updated in #3054

**Comment by noklam** [comment]
I notice that in this [PR](https://github.com/kedro-org/kedro/pull/3081). @amandakys 

```
kedro new --addons="test, docs, log"
```
Should `pyproject.toml` stores this or the other mappings? Should we even have two?

```
ADD_ONS_DICT = {
    "1": "Linting",
    "2": "Testing",
    "3": "Custom Logging",
    "4": "Documentation",
    "5": "Data Structure",
}
```

**Comment by SajidAlamQB** [comment]
> I notice that in this [PR](https://github.com/kedro-org/kedro/pull/3081). @amandakys

I noticed it to, the `ADD_ONS_DICT` is used in the backend for `post_gen_project.py` while the other mappings are just for the cli. Is it worth aligning the naming between the backend and cli?

**Comment by amandakys** [comment]
I think we agreed that the --addons flag would have the shortnames 'lint, docs, test' etc. While in the copy, they are called Linting, Testing, Documentation etc. For the user all they see is the copy, and in the --help they are told what the corresponding shortnames are. 

I think it makes more sense to pick one set of names for the implementation, and the shortnames are probably fine. We can think of the long names as "display/presentation" names and the shortnames as like the "code" names

**Comment by noklam** [comment]
👍🏼, So `pyproject.toml` will keep the long name and CLI will keep the short. I can take the rest from here as it's just implementation details.

**Comment by noklam** [comment]
Just watch the video of the add-ons tech design.

I started some refactoring before watching the video, I share a lot of opinion with @DimedS.

*Pure Function* - @DimedS has a good point. IMO we shouldn't mutate function inputs unless it helps a lot on performance, which I think 99% of the case we shouldn't do it. Even if this has to be done, we should adopt some pattern. For example, in Pytorch there is an user interface `add` function, internally they have a `add_` which actually mutate the tensor.

https://github.com/kedro-org/kedro/pull/3265 is a first step and it can be merged without interfering with existing works, the other refactor will affect PR that are still in progress so I prefer to do it a bit later.
