### ISSUE TITLE
Enhance current integration between Kedro and Ibis

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#4190]
## Description

Given the existing (admittedly-basic) Ibis integration (via `ibis.TableDataset`) has garnered interest and usage, we would like to take some time to address some of the enhancements requested by users (and others that will generally improve Kedro user experience with Ibis backends).

The priorities below are an initial rough prioritization; please comment if certain things (items below and those not yet on the list) would be important for you, your team, or to users you've heard from!

## Issues

- [ ] [P0] https://github.com/kedro-org/kedro-plugins/issues/828
- [ ] [P0] Support writing files to PyArrow/`fsspec`-compatible filesystems
- [ ] [P0] https://github.com/kedro-org/kedro-plugins/issues/833
- [ ] [P0] https://github.com/kedro-org/kedro-plugins/issues/834
- [ ] [P0] https://github.com/kedro-org/kedro-plugins/issues/835
- [ ] [P1] #4189 
- [ ] [P1] Add Kedro-Viz table preview for Ibis datasets
- [ ] [P1] Support passing credentials to Ibis datasets (without custom resolver)
- [ ] [P2] https://github.com/kedro-org/kedro-plugins/issues/725

**Comment by deepyaman** [comment]
Tagging some people I've seen active on both Kedro and Ibis repos or that I know have played with the integration, as would love your thoughts on whether I'm missing things that you all have run into and would like to see addressed, as well as your views on respective priorities of these issues!

@mark-druffel @inigohidalgo @datajoely @galenseilis @gitgud5000 @filipeo2-mck @astrojuanlu @vishu1994

**Comment by galenseilis** [comment]
Related: https://github.com/Galileo-Galilei/kedro-pandera/issues/88#issuecomment-2361916319

**Comment by deepyaman** [comment]
> Related: [Galileo-Galilei/kedro-pandera#88 (comment)](https://github.com/Galileo-Galilei/kedro-pandera/issues/88#issuecomment-2361916319)

Thanks @galenseilis! I've gone ahead and linked that above; didn't know there was already an issue you'd opened covering it. 😄
