### ISSUE TITLE
Enhance Kedro Namespaces adoption

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro#4343]
Kedro namespaces are **currently not widely used**. The team is divided on the reasons for this:

1. Local issues such as incomplete docs, unresolved technical challenges, and potential user concerns about the interface.
2. The namespace feature has been primarily suited for pipeline reusability. However, due to its complexity and lack of successful adoption over the past five years, it may require a significant redesign.

This parent issue aims to facilitate an agreed-upon decision regarding the points above and address these concerns. It is also tied to the goal of improving deployment functionality, where namespaces should play a pivotal role in node grouping.

## History

- [Explanation of namespaces by @idanov, 2020](https://github.com/kedro-org/kedro/wiki/Understanding-namespaces)  
- [2023-11-29 Namespaces TD, Part 1](https://mckinsey.box.com/s/rulk43mod3js7id1f1wbu9pc0qkkszwb)  
- [2023-12-06 Namespaces TD, Part 2](https://mckinsey.box.com/s/kpunyeajg2vnufkgrh6r7yimog7yqodp)  
- [2024-11-20 Namespaces TD, Part 3](https://zoom.us/rec/share/KgKhXg37MGpINoTUS6NtiQUbEY8d4OIf8HNhs5zCJVRBFzW7ypz1XHBGDfxdqvMF.EkxxuznkGKr-B7TV)  
- [Changing modular pipelines terminology GitHub thread](https://github.com/kedro-org/kedro/issues/2723)

---

## Improving docs

- [ ] The current documentation focuses primarily on how namespaces enhance pipeline reusability ([see docs](https://docs.kedro.org/en/stable/nodes_and_pipelines/namespaces.html)). However, this ticket proposes updating the docs to include a clear definition of namespaces, highlighting that they are similar to node tagging but do not allow overlaps. This makes namespaces an excellent choice for creating groups of nodes that can be executed together without conflicts.
Suggested docs example:
 -**Create pipelines without namespaces**: Show how to build basic pipelines.  
 -**Create namespaced pipelines**: Use the initial pipelines to create namespaced versions.  
 -**Combine pipelines**: Build a final pipeline by combining the namespaced ones.  
 -**Visualise**: Include a visualisation using Kedro-Viz 
 -**How to use namespaces for node grouping**: namespaces can be applied directly in the node() creation function. In this case, only the node name is updated with the "namespace_name." prefix
(link to ticket in progress).  

- [ ] #4016 

- [ ] **Clarifying Modularity.** The term "modularity" currently appears to relate to creating pipelines in separate folders, not namespaces. If this interpretation is correct, we should explicitly clarify this distinction in the docs.

---

## Technical issues

Several technical issues were highlighted by @idanov during the last TD. These will be moved here for tracking (details in progress).

---

## User interface

There is a potential user interface concern affecting namespace adoption, which might benefit from design attention (@stephkaiser, @iamelijahko).  

- Namespaces are conceptually similar to tags (but without node overlaps), yet tagging adoption is strong, especially for deployment purposes.
- The **UI** for tags and namespaces differs significantly:
#### **Tagging Example:** [Tags](https://docs.kedro.org/en/stable/nodes_and_pipelines/nodes.html#how-to-tag-a-node) are added directly during node or pipeline creation:
```python
node(func=add, inputs=["a", "b"], outputs="sum", name="adding_a_and_b", tags="node_tag")
```
Alternatively, for pipelines:
```python
my_pipeline = pipeline([...], tags="pipeline_tag")
```
#### **Namespace Example:** Namespaces are applied at the pipeline creation level and involve multiple steps:
1. Create a pipeline without namespaces:
   ```python
   part1 = pipeline([
       node(func=split_data, inputs=["a", "b"], outputs=["c", "d"], name="node1"),
       node(func=split_data, inputs=["c", "d"], outputs=["e", "f"], name="node2"),
   ])
   ```
2. Add a namespace:
   ```python
   part1_ns = pipeline(part1, namespace="part1_ns") # pipeline name most likely repeats namespace name
   ```
   This prefixes all inputs, outputs, and parameters with `part1.`, which most likely not to be desired. To preserve naming:
   ```python
   part1_ns = pipeline(part1, namespace="part1_ns", inputs={"a", "b"}, outputs={"e", "f"})
   # I need to specify my inputs and outputs twice
   ```
3. Combine pipelines in the registry:
   ```python
   my_pipeline = part1_ns + part2_ns + ...
   # Each of my node group - actually a pipeline, but in tags - it's just a tag of a node
   ```

Tags are applied directly to nodes, whereas namespaces require changes at the pipeline level. Simplifying the namespace UI or aligning it more closely with tagging might also improve adoption.

### Few other UI gaps reported by users:
- [ ]  #3448
- [ ] #3679 

## Hackathon
- [ ] Proposed by @Huongg in collaboration with @iamelijahko. Refer to [https://github.com/kedro-org/kedro/issues/4383](https://github.com/kedro-org/kedro/issues/4383)

## Namespaces in deployment

We aim to unify and implement node grouping functionality for deployment purposes in #4319. Namespaces appear to be a great fit for this purpose. However, the ongoing work to increase namespace adoption from the current ticket must be completed on the same time.

**Comment by datajoely** [comment]
Adding a bit of context - deep integration with Kedro-Viz was the first attempt to drive adoption and improve explainability:

- @limdauto published these docs in [October 2021](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/docs/technical_design_expand_collapse_modular_pipelines.md)
- [The earliest version of Kedro-Viz which included this in was tagged for release in Feb 2020](https://github.com/kedro-org/kedro-viz/blob/main/RELEASE.md#release-320)


We have spent nearly 5 years trying to explain this to users in various ways - We must pivot strategy.

**Comment by astrojuanlu** [comment]
Thanks @DimedS for opening this issue.

First, I would like to agree that tags do not guarantee non-overlapping pipeline partitioning. This has been said time and time again.

But I am going to push back against the idea that namespaces are _the_ right solution for that problem. A few reasons:

# Namespaces were probably always designed for pipeline _reuse_

Namespaces were born as "prefixes" and were introduced in Kedro 0.15.4 in October, 2019:

3c0f097991119cce5f42de8844686de104604bf4

(https://github.com/McK-Private/private-kedro/pull/286, private link)

And then in 0.16.0 the modern concept of "modular pipelines" with `namespace` was introduced in March 2020:

af046ca6c738a89e19d6e31ab432a13b0b184190

Therefore a bit less or a bit more than 5 years have passed, depending on how you look at it.

The original context and discussion have forever been lost in time https://jira.quantumblack.com/browse/KED-1105 (broken internal link) but we can get a glimpse of what the _intent_ of the feature was from this comment:

> Nikos pointed me to this and having thought a bunch about vertical pipeline development and pipeline re-use, recently

(https://github.com/McK-Private/private-kedro/pull/286#issuecomment-542717548, private link)

In addition, this is how the documentation of prefixes, and later namespaces, looked like:

- Prefixes https://docs.kedro.org/en/0.15.4/04_user_guide/06_pipelines.html#using-a-modular-pipeline-twice (https://github.com/McK-Private/private-kedro/pull/286, private link)
- Namespaces https://docs.kedro.org/en/0.16.0/04_user_guide/06_pipelines.html#using-a-modular-pipeline-twice (https://github.com/McK-Private/private-kedro/pull/569, private link)

The docs have *always* described namespaces (prefixes) as a way to reuse pipelines. There were _zero_ review comments in those two PRs raising concerns about that.

To note, nobody from the current team participated in the original 0.15 discussion.

Therefore, I can only conclude that **namespaces were always designed for pipeline reuse in mind**.

Implying that namespaces have always been the solution for pipeline non-overlapping partitioning is, in my view, a big unqualified opinion that has no backing in historical written evidence. And as such, saying that "the docs are wrong" is a misrepresentation of what those docs were supposed to describe.

If anything, we're now retrofitting namespaces to solve a problem they weren't intended to solve in the first place. 

---

I am going to push back against doing incremental improvements on a feature that nobody has dared to touch in 5 years, that's difficult to understand even for Kedro engineers, let alone for our users (regardless of their intended use case), and that we're probably retrofitting to solve a problem they weren't designed for.

My recommendation is that we look at the problem of non-overlapping pipeline partitioning with fresh eyes, go back to the drawing board, and prototype.

**Comment by datajoely** [comment]
I would also say from users

- Pipeline reuse is either a solved or minimal problem these days
- Deployment is the much more acute sore sport. Dependency isolation, container granularity all fall into this space and we're not doing a good job of any.

**Comment by DimedS** [comment]
Thank you for your comments, @datajoely and @astrojuanlu. I see that there isn’t a consensus within the team about the future of namespaces, so I’ve updated the header of this issue to reflect your perspectives.

I propose that we continue the discussion about deployment node grouping in the next Tech Design meeting with an open mind to all grouping possibilities - not limited to namespaces. If, during that discussion, we determine that namespaces are essential for deployment, we can revisit this conversation and make a decision on their future.

**Comment by datajoely** [comment]
Great - I'll also link to this write up from last year: 
https://github.com/kedro-org/kedro/wiki/Synthesis-of-research-related-to-deployment-of-Kedro-to-modern-MLOps-platforms

**Comment by deepyaman** [comment]
> Implying that namespaces have always been the solution for pipeline non-overlapping partitioning is, in my view, a big unqualified opinion that has no backing in historical written evidence.

Modular pipelines have long been the solution for non-overlapping pipeline composition. They are the original subunit that you can create with a simple command, and they came with provisions for defining their own set of requirements, packaging, documentation, etc.

Namespaces simply provided a way to enable reuse of modular pipelines without overlapping.

Between modular pipelines and namespaces, you have sufficient power for deployment purposes. You can deploy a full pipeline, or a set of subpipelines.

Tags are OK for running subsets of pipelines, but provide no guarantees around overlapping; it's probably fine if they exist. They don't necessarily have to be a recommended deployment solution.

> Deployment is the much more acute sore sport. Dependency isolation, container granularity all fall into this space and we're not doing a good job of any.

IMO more effectively automatically mapping to containers for orchestration was a minimum bar a couple years ago. This one-way translation was perhaps a good start then. Realistically, modern solutions now provide more aspects of a data platform than just a way to deploy pieces of logic in isolation--they provide lineage, data quality, partial/incremental materialization, etc. These desires are all repeatedly echoed by users, especially data engineers; namespaces are useful, but will go 2% of the way towards providing the full value users expect from data pipelines today.

**Comment by astrojuanlu** [comment]
> Modular pipelines have long been the solution for non-overlapping pipeline composition.

This! Why emulate the concept of hierarchical directories with namespaces when modular pipelines are laid out in actual directories?

**Comment by astrojuanlu** [comment]
Another issue we spotted: https://github.com/kedro-org/kedro/issues/4039

**Comment by astrojuanlu** [comment]
Digging on a recent comment by @noklam :

> [An asset leader] wants to show pipeline as "collapsable" pipeline but he is not using namespace pipeline. In his mind, he thought the keys of `pipeline_registry` is the "collapsable" part

**Comment by datajoely** [comment]
^ On this I would love to proxy tags / registered pipelines which do meet the requirements of a namespace to be thought of as one and collapsed accordingly

**Comment by idanov** [comment]
> ^ On this I would love to proxy tags / registered pipelines which do meet the requirements of a namespace to be thought of as one and collapsed accordingly

I don't think this is a good idea. It's a recipe for more confusion - it's super weird that **something** works only **sometimes** in a **non-obvious way**.

Again, let's refocus the discussion to answer the question, what exactly makes `namespaces` less intuitive than `tags` for example. Without that list of challenges, there's no point of making any decisions, because it'll be all basically an opinion against opinion.

I've shown in my earlier comment that the difference in API is minimal and clearly cannot be the culprit of the issues. There's only one difference there, namely auto-renaming of datasets behind the scenes. Shall we not dig in there first to see if we can improve that before actually suggesting we go ahead with some other random ideas like repurposing tags, registered pipelines and what-not?

**Comment by MatthiasRoels** [comment]
In this whole discussion about tags and namespaces, I never really understood why we need 3 concepts to group nodes (tags, pipelines and namespaces). To me, it feels weird to have to "force" a user to create a bunch of pipelines. But when it comes to deployment, you completely forget about this concept and you would need another concept (a namespace or a tag) to make it work. 

Wouldn't a better alternative be that we think about a pipeline as a "main" function calling several other functions (nodes in this case). That pipeline could then have an input and output defined that is used in de nodes. When designing it right, it should be enough to only have those inputs and outputs defined in the catalog. Again, following the analogy with coding, the objects you return in your main function are the only variables you have access to later on (references to all other objects are lost). 

So when you then want to add two pipelines, you have the following scenarios depending on what the graphs look like:

- option 1: you have `pipeline_1` with inputs `A, B` and outputs `C, D` and a `pipeline_2` with inputs `E, F` and outputs `G, H` so the sum is a pipeline `pipeline_1 + pipeline_2` with inputs `A, B, E, F` and outputs `C, D, G, H`
- option 2: you have `pipeline_1` with inputs `A, B` and outputs `C, D` and a `pipeline_2` with inputs `A, E` and outputs `G, H` so the sum is a pipeline `pipeline_1 + pipeline_2` with inputs `A, B, E` and outputs `C, D, G, H`
- option 3: you have `pipeline_1` with inputs `A, B` and outputs `C, D` and a `pipeline_2` with inputs `B, C` and outputs `G, H` so the sum is a pipeline `pipeline_1 + pipeline_2` with inputs `A, B` and outputs `C, D, G, H`
- unless I forgot another valid option, all other options should result in a descriptive error that summation is impossible. 

In this scenario, as @astrojuanlu and @noklam mentioned, the keys of the pipelines in the registry are then the ones suitable to collapse (and also used in deployment). As a result, in the deployments, you will see very simple commands like `kedro run --env=... --pipeline=...` instead of complex ones with `kedro run --from-nodes=... --to-nodes=...`

**Comment by DimedS** [comment]
During her work on node grouping, @ankatiyar discovered that namespaces can be applied directly in the node() creation function. In this case, only the node name is updated with the "namespace_name." prefix. This functionality can be useful for UI purposes when using namespaces for node grouping. It works similarly to tags, eliminating the need to create an additional pipeline solely for grouping nodes. Additionally, it avoids the need to rename inputs and outputs afterward.

Currently, this feature is not documented, so it makes sense to add a new section, "How to use namespaces for node grouping," alongside the existing "How to reuse pipelines with namespaces." I will update the top post here to include this information and create a GitHub issue for it.

We are also working on revising the current UI for namespaces at the pipeline level and exploring how Kedro-Viz capabilities can enhance the user experience.

**Comment by astrojuanlu** [comment]
Oh wow, that's surprising. Although it shouldn't be really, it was there all this time...

https://github.com/kedro-org/kedro/blob/5e81f547bf2d0c07bc99a47b63d773081bd1bcfb/kedro/pipeline/node.py#L581

Does it require updating the inputs and outputs names as well?

Regardless, I fail to see how node-specific namespaces emulate the concept of directories, which is what guarantees a non-overlapping partitioning of the DAG from a mathematical perspective, hence in theory enabling conflict-free deployment.

**Comment by astrojuanlu** [comment]
We have a parent issue about improving node grouping for deployment #4319 

And a sub-task to conduct user testing to understand why the adoption is low #4382 

The discussion here is useful but I don't think we should guide ourselves by "let's improve adoption of a specific feature", but rather to always seek a deep understanding of the user problem. Everything else is in service of that. If namespaces aren't solving the user problem they were supposed to solve they should improve (with that target in mind), or be replaced by some other solution.

I'm closing this issue until we have more clarity on the way forward.
